// Generated by https://quicktype.io

export interface Entrega {
  id: string;
  scoutId: string;
  tipoEntrega: string;
  fechaEntrega: string;
  fechaCreacion: string;
  scout: Scout;
}

export interface Scout {
  nombre: string;
  apellido: string;
  dni: string;
  funcion: string;
  fechaNacimiento: string;
  sexo: string;
  telefono: string;
}
