// Generated by https://quicktype.io

import { VALID_METODOS_PAGO } from "validators/constants";

export interface Pago {
  id: string;
  concepto: string;
  monto: string;
  rendido: boolean;
  // metodoPago: typeof VALID_METODOS_PAGO;
  metodoPago: string;
  scoutId: string;
  fechaPago: string;
  fechaCreacion: string;
}
